title: "Resource Manager Example VCN by TheKoguryo"
description: "Resource Manager로 VCN을 만드는 예제입니다."
schemaVersion: 1.0.0
version: "20220119"

locale: "en"
groupings:
  - title: "Basic Hidden"
    visible: false
    variables:
    - compartment_ocid
    - tenancy_ocid
    - region

  - title: "Basic Configuration"
    variables:
    - vcn_name
    - vcn_dns_label

  - title: "Configure VCN"
    variables: 
    - vcn_cidr_block    

variables:
  vcn_name:
    type: string
    title: VCN Name
    required: true
    default: example_vcn

  vcn_dns_label:
    type: string
    title: VCN DNS Label
    description: "Only letters and numbers, starting with a letter. 15 characters max." 
    required: true
    default: examplevcn  

  vcn_cidr_block:
    type: list(string)
    title: VCN IPv4 CIDR Block
    description: "Example: 10.0.0.0/16"    
    required: true    
    default: ["10.0.0.0/16"]    